AWSTemplateFormatVersion: '2010-09-09'
Resources:
  MyAmplifyApp:
    Type: 'AWS::Amplify::App'
    Properties:
      Name: 'MyStaticSite'  # The name of your Amplify app
      Repository: 'https://github.com/your-username/your-repository'  # The URL of your GitHub repository
      OauthToken: '{{resolve:ssm:/path/to/github/oauth/token}}'  # GitHub OAuth token stored in SSM
      AccessToken: 'YOUR_GITHUB_ACCESS_TOKEN'  # Access token for the repo (can also be an SSM parameter)
      Branches:
        - BranchName: 'main'
          Stage: 'PRODUCTION'
          Framework: 'None'
          EnvironmentVariables:
            - Name: 'S3_BUCKET_NAME'
              Value: 'YOUR_BUCKET_NAME'
          EnableAutoBuild: true
          EnableBasicAuth: false
          AutoBranchCreationConfig:
            Stage: 'PRODUCTION'
            EnableAutoBuild: true
            EnableBasicAuth: false
            BasicAuthCredentials: ''
      BuildSpec:
        Version: 0.2
        Phases:
          build:
            commands:
              - echo "Building app for Amplify"
              - npm install
              - npm run build  # Customize if you have a build process
        Artifacts:
          Files:
            - '**/*'
          BaseDirectory: 'dist'  # The directory with your build output
        Cache:
          Paths:
            - node_modules/**/*  # If using npm or yarn, you can cache node_modules

  MyAmplifyBranch:
    Type: 'AWS::Amplify::Branch'
    Properties:
      AppId: !Ref 'MyAmplifyApp'
      BranchName: 'main'
      EnableAutoBuild: true
      EnableBasicAuth: false
      Stage: 'PRODUCTION'
      EnvironmentVariables:
        - Name: 'S3_BUCKET_NAME'
          Value: 'YOUR_S3_BUCKET_NAME'
